---
openapi: 3.0.1
info:
  title: Get more properties API
  version: v1
paths:
  "/api/v1/users":
    post:
      summary: Sign up
      tags:
      - users
      parameters: []
      responses:
        '401':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                client_id:
                  type: string
              required:
              - name
              - email
              - password
              - client_id
  "/api/v1/oauth/token":
    post:
      summary: Sign in
      tags:
      - users
      parameters: []
      responses:
        '401':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                email:
                  type: string
                password:
                  type: string
                client_id:
                  type: string
                client_secret:
                  type: string
              required:
              - email
              - password
              - grant_type
              - client_id
              - client_secret
   "/api/v1/properties":
    parameters:
    - name: Authorization
      in: header
      description: bearer xyz
      schema:
        type: string
    get:
      summary: list properties
      tags:
      - properties 
      responses:
        '401':
          description: Invalid request
        '200':
          description: Success
          content:
          application/json:
              example:
                - id: 1
                  name: Example Property 1
                  image: https://photo.com
                  price: 40000
                  reserve: false
                  location: Accra
                - id: 2
                  name: Example Property 2
                  image: https://photo2.com
                  price: 10000
                  reserve: false
                  location: Nairobi
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    image:
                      type: string
                    price:
                      type: number
                    reserve:
                      type: boolean
                    location:
                      type: string
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com